# -*- coding: utf-8 -*-
"""Source of truth for the dashboard's Changelog tab (site_changelog Firestore
collection). Add new entries at the bottom of this list each week, then run
scripts/sync_changelog.py to push them - it only writes date/week_label/
category/title/detail/impact/link/status/order per doc, so it never touches
the `comments` field and is safe to re-run for old items too.
"""

SITE = "https://dentalofficemanagers.com"

CHANGELOG = [
    # --- Week of Sep 15-18, 2026 ---
    {"id": "2026-09-15_00", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Fixed 5 broken internal links and title/description length issues", "detail": "Sitewide sweep of Yoast titles and descriptions.", "impact": "Fewer 404s hit by users and Google's crawler; less drag on crawl budget.", "link": None, "status": "done", "order": 0},
    {"id": "2026-09-15_01", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": 'Fixed a content gap on "dental coaching"', "detail": "Page ranked for the term but never used the exact phrase on the page.", "impact": "Closes the gap between what Google ranked the page for and what the page actually said.", "link": None, "status": "done", "order": 1},
    {"id": "2026-09-15_02", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Confirmed a sustained ranking improvement", "detail": "Average position trend: 16.6 -> 13.9 -> 12.4 -> 12.5 over 4 weeks, matching the fix rollout.", "impact": "Confirmed with real Search Console data: average position 16.6 -> 13.9 -> 12.4 -> 12.5 over 4 weeks.", "link": None, "status": "done", "order": 2},
    {"id": "2026-09-15_03", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Site speed", "title": "Fixed ebook page LCP (10s load time)", "detail": "A GoHighLevel form embed was blocking first paint; now lazy-loaded.", "impact": "Page load speed is a Core Web Vitals ranking signal; page now loads fast instead of ~10s.", "link": None, "status": "done", "order": 3},
    {"id": "2026-09-15_04", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Sponsors", "title": "Removed Mark3; fixed Roya/Janie logo sizing; added Cherry and Vyne Dental", "detail": "Applied to homepage carousel, /offers/, and dashboard; sponsors reordered alphabetically.", "impact": "Keeps sponsor logos and directory accurate and current on both the site and the dashboard.", "link": f"{SITE}/offers/", "status": "done", "order": 4},
    {"id": "2026-09-15_05", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Sponsors", "title": "Updated Janie.ai listing per their request", "detail": 'New description and offer ("one month free" replacing the DOMA50 code).', "impact": "Matches what Janie.ai is actually offering right now instead of an expired code.", "link": f"{SITE}/offers/", "status": "done", "order": 5},
    {"id": "2026-09-15_06", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Content", "title": 'Replaced a dead "Events" sidebar block with a "Become a Sponsor" card', "detail": "Shared blog template, ~300 posts. Iterated twice on the design; corrected the link to /partner/.", "impact": "Every one of ~300 posts now promotes sponsorship instead of showing a dead block.", "link": None, "status": "done", "order": 6},
    {"id": "2026-09-15_07", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Compliance", "title": "Built Google Consent Mode v2 and a custom cookie banner", "detail": "The Complianz plugin was installed but never configured, so no banner was showing. Built one from scratch; fixed a mobile layout bug in it.", "impact": "Site is now compliant with Google's consent requirements instead of running unconfigured.", "link": SITE, "status": "done", "order": 7},
    {"id": "2026-09-15_08", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Marketing", "title": "Split the Email Campaigns dashboard tab by platform", "detail": 'Corrected an ActiveCampaign-vs-GHL attribution mix-up using raw CSV exports; relabeled a misleading "Total recipients" metric.', "impact": "Team now sees real per-platform numbers instead of a merged, misattributed total.", "link": None, "status": "done", "order": 8},
    {"id": "2026-09-15_09", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Dashboard & task cleanup", "title": "Found and fixed a status-sync bug; cleared the task backlog", "detail": "SQLite-only status updates silently failed when a live override existed elsewhere. Fixed 8 items directly, closed 2 more tickets per Kyle's request.", "impact": "8 stuck tasks no longer silently out of sync; team board reflects reality.", "link": None, "status": "done", "order": 9},
    {"id": "2026-09-15_10", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Dashboard & task cleanup", "title": "Merged meeting action items into the To Do board", "detail": "Previously separate collections; preserved correct edit/delete/comment behavior per source.", "impact": "One board instead of two separate ones; nothing falls through the cracks.", "link": None, "status": "done", "order": 10},
    {"id": "2026-09-15_11", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Dashboard & task cleanup", "title": "Weekly Recap now shows the full meeting transcript", "detail": "Added an expandable section instead of just a short summary.", "impact": "Anyone can verify what was actually said in a meeting, not just a short summary.", "link": None, "status": "done", "order": 11},
    {"id": "2026-09-15_12", "date": "2026-09-15", "week_label": "Week of Sep 15-18, 2026", "category": "Dashboard & task cleanup", "title": "Investigated reported dashboard bugs", "detail": "Recap/to-do not showing, dark title text. Not reproducible on a clean load; concluded browser-cache or forced-dark-mode on the reporters' own machines.", "impact": "Ruled out a real site bug; saved time chasing a false report.", "link": None, "status": "done", "order": 12},
    {"id": "2026-09-15_13", "date": "2026-09-16", "week_label": "Week of Sep 15-18, 2026", "category": "Content", "title": "Fixed 30 posts with broken featured images", "detail": "Images had a corrupted aspect ratio (a stray gradient sliver, not a real photo); replaced with a proper fallback.", "impact": "30 posts no longer show a broken thumbnail in search results or social shares.", "link": None, "status": "done", "order": 13},
    {"id": "2026-09-15_14", "date": "2026-09-16", "week_label": "Week of Sep 15-18, 2026", "category": "Sponsors", "title": "Removed Yeah Dental and DayDream Dental (no longer partners)", "detail": "Removed from homepage, /offers/, and dashboard directory; fixed a layout break this caused.", "impact": "No dead partner listings shown to visitors.", "link": f"{SITE}/offers/", "status": "done", "order": 14},
    {"id": "2026-09-15_15", "date": "2026-09-16", "week_label": "Week of Sep 15-18, 2026", "category": "Sponsors", "title": "Fixed broken Mango Voice link", "detail": "Replaced an outdated tracking URL with the working link.", "impact": "Visitors clicking that sponsor link land on a working page instead of a dead one.", "link": f"{SITE}/offers/", "status": "done", "order": 15},
    {"id": "2026-09-15_16", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": 'Fixed keyword cannibalization on "dental office management"', "detail": "The homepage was outranking our own pillar page. Added an internal link so the pillar page gets credit.", "impact": "Pillar page can now win the ranking instead of competing with the homepage for the same term.", "link": None, "status": "done", "order": 16},
    {"id": "2026-09-15_17", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Consolidated a duplicate-content pair", "detail": "Two posts covered the same checklist topic and were competing in search. One now points to the other as canonical.", "impact": "Two pages no longer split ranking signal for the same topic.", "link": None, "status": "done", "order": 17},
    {"id": "2026-09-15_18", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Rewrote title/description for top-ranking coaching post", "detail": "Ranked around position 9 but had zero clicks. New title and description written for click-through.", "impact": "Higher click-through expected at the same ranking position (~9).", "link": None, "status": "done", "order": 18},
    {"id": "2026-09-15_19", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Removed 22 old, thin posts from Google's index", "detail": "They weren't earning traffic and were dragging down the site's overall quality signal. Noindexed, not deleted.", "impact": "Removes a drag on the site's overall content-quality signal in Google's eyes.", "link": None, "status": "done", "order": 19},
    {"id": "2026-09-15_20", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Fixed 2 ebook page pairs with missing SEO data", "detail": "Task Calendar and Front Desk Duty Roster: thank-you pages were indexable when they shouldn't be; landing pages were missing descriptions.", "impact": "Thank-you pages no longer compete in search; landing pages show a real description in results.", "link": None, "status": "done", "order": 20},
    {"id": "2026-09-15_21", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": 'Diagnosed an Ahrefs report showing "broken" pages spiking', "detail": "Root cause: the hosting firewall blocks Ahrefs' and Semrush's crawlers. Google and Bing are unaffected, not a real site issue.", "impact": "Confirmed no real site health issue - the firewall blocks 3rd-party crawlers, not Google or Bing.", "link": None, "status": "done", "order": 21},
    {"id": "2026-09-15_22", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "Site speed", "title": "Fixed slow-loading hero images", "detail": "/forms/ 54->69, /courses/ 58->83, /offers/ 66->88 (PageSpeed score). Main image load time dropped from ~9s to 3.7-5.6s.", "impact": "/forms/ 54->69, /courses/ 58->83, /offers/ 66->88 PageSpeed score. Load time ~9s -> 3.7-5.6s.", "link": f"{SITE}/offers/", "status": "done", "order": 22},
    {"id": "2026-09-15_23", "date": "2026-09-17", "week_label": "Week of Sep 15-18, 2026", "category": "Content", "title": "Added an FAQ section to the AI Guides landing page", "detail": "Page was too thin (291 words). Added real content below the signup form without touching conversion.", "impact": "Page now has enough real content to be considered useful/indexable, without touching the form's conversion.", "link": None, "status": "done", "order": 23},
    {"id": "2026-09-15_24", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Fixed a site-wide bug affecting every blog post", "detail": "All ~300 posts sent Google an empty page, title and body only appeared after JavaScript ran. Content is now in the raw HTML for every post.", "impact": "Google was previously served an empty page for every post; content is now visible on first load, sitewide.", "link": None, "status": "done", "order": 24},
    {"id": "2026-09-15_25", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Fixed wrong domain in structured data", "detail": "An old rebrand leftover was telling Google the wrong site domain, including in the site search function.", "impact": "Google's structured data (including the site search box) now points at the real domain, not an old rebrand.", "link": None, "status": "done", "order": 25},
    {"id": "2026-09-15_26", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "SEO", "title": "Fixed missing meta description on the newest ebook page", "detail": "Insurance Verification landing page.", "impact": "Page can show a real description in search results instead of Google auto-generating one.", "link": None, "status": "done", "order": 26},
    {"id": "2026-09-15_27", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "Design & UX", "title": 'Fixed mobile cookie banner covering the "Become a Member" button', "detail": "Shortened the banner on mobile; kept the buttons at an accessible touch-target size.", "impact": '"Become a Member" button fully clickable on mobile again; banner still meets accessibility touch-target size.', "link": SITE, "status": "done", "order": 27},
    {"id": "2026-09-15_28", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "Design & UX", "title": "Removed a duplicate-title effect behind blog post headers", "detail": "The background image had the post title baked into it, faintly visible behind the real title. Now blurred.", "impact": "Removed a distracting visual artifact behind every post header and the homepage hero.", "link": SITE, "status": "done", "order": 28},
    {"id": "2026-09-15_29", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "Design & UX", "title": "Fixed a visible seam in the top navigation", "detail": "Removed an unintended border line between the utility bar and main nav.", "impact": "Cleaner, more polished look in the header on every page.", "link": SITE, "status": "done", "order": 29},
    {"id": "2026-09-15_30", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "Design & UX", "title": "Increased a few label font sizes that were too small", "detail": "Homepage eyebrow and section labels, 11px -> 12.5px.", "impact": "Improves readability of small labels on the homepage.", "link": SITE, "status": "done", "order": 30},
    {"id": "2026-09-15_31", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "Design & UX", "title": "Corrupted alt text found on related-post thumbnails", "detail": "One post's title has an apostrophe that renders as a broken character in image alt text. Root cause found in the template's JavaScript; fix not yet applied.", "impact": "Fix identified, not yet applied - affects alt text on related-post thumbnails only, no visible impact yet.", "link": None, "status": "in_progress", "order": 31},
    {"id": "2026-09-15_32", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "Dashboard & task cleanup", "title": "Closed 3 more content-related tasks", "detail": "Article publishing, podcast repurposing, event media collection.", "impact": "Team task backlog reduced by 3 items.", "link": None, "status": "done", "order": 32},
    {"id": "2026-09-15_33", "date": "2026-09-18", "week_label": "Week of Sep 15-18, 2026", "category": "Tooling", "title": "Set up SEO, data, task, marketing, and design tools", "detail": "SearchFit SEO, Data, Productivity, Marketing, ActiveCampaign, and Design skills installed for this project going forward.", "impact": "Sets up faster SEO/design/data work on this project going forward.", "link": None, "status": "done", "order": 33},

    # --- Add next week's items below this line ---
]
